### ISSUE TITLE
Object alignment in Medium page

### ISSUE THREAD

**Issue by taotao365s** [chenghanpeng/jdk11u#1]
114页，第7行，
````
中页面大小为32M，对象按照256KB对齐，所以最多可以存放128个对象
````
源码中注释，中页面对象是按**_4K_**对齐的
![image](https://user-images.githubusercontent.com/1212932/65823534-a69a3900-e28a-11e9-8849-03e075c5cf39.png)
http://hg.openjdk.java.net/zgc/zgc/file/59c07aef65ac/src/hotspot/os_cpu/linux_x86/zGlobals_linux_x86.hpp#l34

**Comment by chenghanpeng** [comment]
不好意思，确实如此。可能当时看花眼了，不知道怎么一直都是按照256K来计算，文中可能还有其他的地方，比如P91。多谢！！
