### ISSUE TITLE
“在ZGC中强制开启偏向锁无效”的描述有误

### ISSUE THREAD

**Issue by yansendao** [chenghanpeng/jdk11u#2]
平台： linux x64-64

版本：11.0.5

```
$ java -version
openjdk version "11.0.5" 2019-10-15
```

原文描述：

在ZGC中会重置该参数为false，禁止偏向锁性能更好，即使强制打开该参数也无效。

强制开启ZGC和偏向锁：

![image](https://user-images.githubusercontent.com/36258307/71567017-00fb9d80-2af7-11ea-95d6-fa0a021705c5.png)

**Comment by chenghanpeng** [comment]
抱歉，UseNUMA也应该有同样的问题
